### ISSUE TITLE
Quiz Log View

### ISSUE THREAD

**Issue by dmosc** [PatoGuereque/Learn-to-Py#6]
Desarrollar vista para mostrar un log de resultados de ejercicios pasados para visualizar el progreso de comprensión.

- [ ] La vista sigue el diseño establecido en el [wireframe](https://www.figma.com/file/rbb4eHQgVQQeextfLkSBK6/Views?node-id=0%3A1).
- [ ] Utilizar UserDefaults para cargar los resultados de la memoria local del celular.

**Comment by PatoGuereque** [comment]
Closed because #14 was merged
